@startuml
skinparam componentStyle uml2
actor Пользователь as User
actor Администратор as Admin


component "Сервис системы лояльности" as LoyaltyService #Yellow {
    component "AdminPanel" {
        [Backend (Django)] as Django
    }

    component "API" as API

    database "Redis" as Redis {
        [Хранение промокодов] as PromocodeStorage
    }
    database "PostgreSQL" as PostgreSQL {
        [Хранение информации о покупках и скидках] as Orders
    }
}

component "WebApp" as WebApp


component "Сервисы онлайн-кинотеатра" as OtherServices {
    component "Сервис авторизации" as AuthService
    component "Сервис нотификации" as NotificationService
    component "Сервис биллинга" as BillingService
}

interface JWT_SECRET
note left of JWT_SECRET
    Сервисы используют общий JWT Secret
    для генерации/проверки токена соответственно
end note


Admin -down-> AdminPanel: Управление скидками и промокодами
User --> WebApp: Запрос на создание заказа
WebApp --> API: Запрос на создание заказа
API <--> PostgreSQL
API <--> Redis
Django <--> PostgreSQL
API .up.> NotificationService
NotificationService ..> User: Отправка уведомления
BillingService <..> API: Информация для оплаты заказа

LoyaltyService .up. JWT_SECRET
AuthService .. JWT_SECRET


@enduml