@startuml
actor Пользователь as User
participant "Сервис\nконтента" as ContentService
participant "Сервис\nавторизации" as AuthService
participant "Сервис\nлояльности" as LoyaltyService
participant "Сервис\nбиллинга" as BillingService
participant "Сервис\nнотификации" as NotificationService

User -> ContentService: Запрос на выдачу фильма
ContentService -> AuthService: Запрос на авторизацию
AuthService --> ContentService: Ответ на запрос авторизации
ContentService -> LoyaltyService: Запрос информации о скидке на фильм
LoyaltyService -> AuthService: Запрос информации о наличии подписки у пользователя
AuthService --> LoyaltyService: Информация о наличии подписки у пользователя
LoyaltyService --> ContentService: Информация о скидке на фильм
ContentService -> User: Выдача фильма и информации о нем с учетом скидок

User -> ContentService: Запрос на покупку фильма


ContentService --> BillingService: Информация для оплаты фильма (в том числе скидка)
BillingService -> LoyaltyService: Запрос наличия скидки на фильм и указанного пользователем промокода
LoyaltyService --> BillingService: Ответ о наличии скидки на фильм и указанного пользователем промокода

BillingService --> LoyaltyService: Информация об использовании скидки и/или промокода при успешном заказе
note left: удаление промокода, если он одноразовый
note left
- запись факта использования промокода и/или скидки
- удаление промокода, если он одноразовый
end note
BillingService -> NotificationService: Запрос на отправку оповещения пользователю
NotificationService --> User: Отправка оповещения пользователю
@enduml