# Generated by Django 4.1.5 on 2023-01-24 15:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='value')),
                ('enabled', models.BooleanField(default=False, verbose_name='enabled')),
                ('period_begin', models.DateField(verbose_name='start_date')),
                ('period_end', models.DateField(verbose_name='end_date')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'db_table': 'loyalty"."discount',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('months', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='months')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'loyalty"."subscription',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.UUIDField(verbose_name='user')),
                ('status', models.IntegerField(choices=[(0, 'CREATED'), (1, 'IN_PROCESS'), (2, 'PAID'), (3, 'CANCELED')], verbose_name='status')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loyalty.discount', verbose_name='discount')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loyalty.subscription', verbose_name='subscription')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'loyalty"."order',
            },
        ),
        migrations.AddField(
            model_name='discount',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyalty.subscription', verbose_name='subscription'),
        ),
    ]
