# Generated by Django 4.1.5 on 2023-01-29 15:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.UUIDField(verbose_name='user')),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='value')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('expiration_date', models.DateTimeField(verbose_name='expiration_date')),
                ('measure', models.CharField(choices=[('%', '%'), ('RUB', 'RUB')], max_length=5, verbose_name='measure')),
                ('is_multiple', models.BooleanField(default=False, verbose_name='is_multiple')),
            ],
            options={
                'verbose_name': 'Promocode',
                'verbose_name_plural': 'Promocodes',
                'db_table': 'loyalty"."promocode',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('months', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='months')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'loyalty"."subscription',
            },
        ),
        migrations.CreateModel(
            name='PromoUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.UUIDField(verbose_name='user')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyalty.promocode', verbose_name='promo')),
            ],
            options={
                'verbose_name': 'PromoUsage',
                'verbose_name_plural': 'PromoUsages',
                'db_table': 'loyalty"."promo_usage',
            },
        ),
        migrations.CreateModel(
            name='DiscountSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='value')),
                ('enabled', models.BooleanField(default=False, verbose_name='enabled')),
                ('period_begin', models.DateTimeField(verbose_name='start_date')),
                ('period_end', models.DateTimeField(verbose_name='end_date')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyalty.subscription', verbose_name='subscription')),
            ],
            options={
                'verbose_name': 'Subscription discount',
                'verbose_name_plural': 'Subscription discounts',
                'db_table': 'loyalty"."discount_subscription',
            },
        ),
        migrations.CreateModel(
            name='DiscountFilms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('tag', models.CharField(max_length=50, verbose_name='tag')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='value')),
                ('enabled', models.BooleanField(default=False, verbose_name='enabled')),
                ('period_begin', models.DateTimeField(verbose_name='start_date')),
                ('period_end', models.DateTimeField(verbose_name='end_date')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyalty.subscription', verbose_name='subscription')),
            ],
            options={
                'verbose_name': 'Film discount',
                'verbose_name_plural': 'Film discounts',
                'db_table': 'loyalty"."discount_film',
            },
        ),
    ]
